# Generated by Django 5.0 on 2023-12-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_id',
        ),
    ]
